# Generated by Django 2.1.4 on 2019-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190129_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createplotmodel',
            name='roadno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createplotmodel',
            name='surveyno',
            field=models.IntegerField(),
        ),
    ]
