# Generated by Django 2.1.4 on 2019-02-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createplotmodel',
            name='totalcost',
            field=models.IntegerField(default=True),
        ),
    ]
