# Generated by Django 2.1.4 on 2019-02-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_createplotmodel_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createplotmodel',
            name='totalcost',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
    ]
