# Generated by Django 2.1.4 on 2019-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190201_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('plotno', models.IntegerField(primary_key=True, serialize=False)),
                ('salevalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateofsale', models.DateField()),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
