# Generated by Django 2.1.4 on 2019-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_salesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='installment',
            field=models.CharField(max_length=10),
        ),
    ]
