# Generated by Django 2.1.4 on 2019-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_salesmodel_soldto'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='check',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='payeename',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
